/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vicxqh.srp;

import vicxqh.srp.agent.Agent;

public class App {
    public static void main(String[] args) {
        Agent agent = new Agent("65.52.171.89:8010", "java-client", "java-client");
        agent.run();
    }
}
